name: ct_micro_commons_dependencies
description: 
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: 5.0.3
  mobx: 2.1.3
  flutter_mobx: 2.0.6+5
  url_strategy: 0.2.0
  dio: 4.0.6
  shared_preferences: 2.0.17
  google_fonts: 4.0.0
  fluttertoast: 8.0.9
  responsive_ui: 3.0.0
  responsive_grid: 2.1.0
  localization: 2.1.0
  skeletons: 0.0.3
  logger: 1.3.0
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
  assets:
    - assets/lang/
    